# Generated by Django 5.0.6 on 2024-05-21 01:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerView',
            fields=[
                ('pid', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('profile_picture_url', models.URLField(null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('introduction', models.CharField(max_length=200, null=True)),
                ('ptype', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=90, null=True)),
                ('authentication', models.CharField(max_length=90, null=True)),
            ],
            options={
                'db_table': 'producer_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SongView',
            fields=[
                ('sid', models.UUIDField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=45)),
                ('aid', models.UUIDField()),
                ('aname', models.CharField(max_length=45)),
                ('cover_url', models.URLField(null=True)),
                ('pid', models.UUIDField()),
                ('username', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'song_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('cid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=45)),
                ('profile_picture_url', models.URLField(null=True)),
                ('music_type', models.CharField(max_length=60)),
                ('introduction', models.CharField(max_length=200)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdinaryUser',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('profile_picture_url', models.URLField(null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('birthday', models.DateField(null=True)),
                ('region', models.CharField(max_length=45, null=True)),
                ('introduction', models.CharField(max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ptype', models.CharField(max_length=20, null=True)),
                ('title', models.CharField(max_length=90, null=True)),
                ('authentication', models.CharField(max_length=90, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('bid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('content_url', models.URLField(null=True)),
                ('likes', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.community')),
                ('ordinaryUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.ordinaryuser')),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('bcid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=400)),
                ('release_time', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.blog')),
                ('ordinaryUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.ordinaryuser')),
            ],
        ),
        migrations.AddField(
            model_name='ordinaryuser',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='musicplayer.producer'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('aid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aname', models.CharField(max_length=45)),
                ('atype', models.CharField(max_length=20, null=True)),
                ('release_date', models.DateField(null=True)),
                ('introduction', models.CharField(max_length=200, null=True)),
                ('cover_url', models.URLField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.producer')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('sid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('audio_url', models.URLField(null=True)),
                ('lyrics_url', models.URLField(null=True)),
                ('sname', models.CharField(max_length=45)),
                ('stype', models.CharField(max_length=20, null=True)),
                ('sversion', models.CharField(max_length=20, null=True)),
                ('language_type', models.CharField(max_length=45, null=True)),
                ('music_style', models.CharField(max_length=45, null=True)),
                ('metadata', models.CharField(max_length=200, null=True)),
                ('introduction', models.CharField(max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.album')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.producer')),
            ],
        ),
        migrations.CreateModel(
            name='SongComment',
            fields=[
                ('scid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=400)),
                ('release_time', models.DateTimeField(auto_now=True)),
                ('ordinaryUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.ordinaryuser')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.song')),
            ],
        ),
        migrations.CreateModel(
            name='SongList',
            fields=[
                ('slid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('cover_picture_url', models.URLField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('ordinaryUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.ordinaryuser')),
            ],
        ),
        migrations.CreateModel(
            name='SongAndCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.community')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.song')),
            ],
            options={
                'unique_together': {('song', 'community')},
            },
        ),
        migrations.CreateModel(
            name='SongAndProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=20)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.producer')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.song')),
            ],
            options={
                'unique_together': {('producer', 'song')},
            },
        ),
        migrations.CreateModel(
            name='SongAndSongList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_time', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.song')),
                ('songList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.songlist')),
            ],
            options={
                'unique_together': {('songList', 'song')},
            },
        ),
        migrations.CreateModel(
            name='UserFollowCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('follow_time', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.community')),
                ('ordinaryUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.ordinaryuser')),
            ],
            options={
                'unique_together': {('ordinaryUser', 'community')},
            },
        ),
        migrations.CreateModel(
            name='UserFollowProducer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_time', models.DateTimeField(auto_now=True)),
                ('ordinaryUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.ordinaryuser')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicplayer.producer')),
            ],
            options={
                'unique_together': {('producer', 'ordinaryUser')},
            },
        ),
    ]
