# Generated by Django 5.0.6 on 2024-05-21 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songandproducer',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songandproducer',
            name='status',
            field=models.CharField(default='p', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songandproducer',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
