# Generated by Django 5.0.6 on 2024-05-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0002_songandproducer_create_time_songandproducer_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content_url',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
