# Generated by Django 5.0.6 on 2024-06-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0003_remove_blog_content_url_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
    ]
